### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by deepakbhor** [131/xterm2#1]
Hello,

I got below error while installing xterm2 during npm install. I am new to npm installation , appreciate your help on this.

silly lifecycle pty.js@0.3.1~install: Returned: code: 1  signal: null
info lifecycle pty.js@0.3.1~install: Failed to exec install script
verbose stack Error: pty.js@0.3.1 install: `node-gyp rebuild`
verbose stack Exit status 1
verbose stack     at EventEmitter.<anonymous> (E:\nodeV8\node_modules\npm\lib\utils\lifecycle.js:283:16)
verbose stack     at emitTwo (events.js:125:13)
verbose stack     at EventEmitter.emit (events.js:213:7)
verbose stack     at ChildProcess.<anonymous> (E:\nodeV8\node_modules\npm\lib\utils\spawn.js:40:14)
verbose stack     at emitTwo (events.js:125:13)
verbose stack     at ChildProcess.emit (events.js:213:7)
verbose stack     at maybeClose (internal/child_process.js:897:16)
verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
verbose pkgid pty.js@0.3.1

**Comment by MaximeAnsquer** [comment]
Same problem here.
